from django.contrib import admin
from django.urls import path
from operasional.views import (
    list_pelanggan,
    tambah_pelanggan,
    edit_pelanggan,
    hapus_pelanggan,
    history_kasbon_pelanggan,
    profil_petani,
    buat_nota, 
    laporan_harian,
    info_kas, 
    tambah_saldo, 
    transaksi_kasbon, 
    list_tanggungan,
    lunasin_bb, 
    selesaikan_tf, 
    info_tonase, 
    tambah_pengeluaran,
    edit_transaksi,
    list_pengiriman_aktif, 
    buat_pengiriman, 
    detail_pengiriman, 
    tambah_item_pengiriman, 
    finalisasi_pengiriman, 
    laporan_pengiriman, 
    item_belum_nota,
    # --- FUNGSI BARU UNTUK LOT & PABRIK ---
    get_lots,
    buat_lot,
    get_lot_detail,
    edit_pengiriman_pabrik,
    edit_lot,
    hapus_lot,
    edit_item_pengiriman,
    hapus_item_pengiriman,
    hapus_nota,
    hapus_transaksi,
    hapus_kasbon_entry,
    hapus_pengiriman,
    api_login,
    list_log_aktivitas,
    prediksi_harga_ai,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('api/pelanggan/', list_pelanggan, name='list_pelanggan'),
    path('api/pelanggan/tambah/', tambah_pelanggan, name='tambah_pelanggan'),
    path('api/pelanggan/edit/', edit_pelanggan, name='edit_pelanggan'),
    path('api/pelanggan/hapus/', hapus_pelanggan, name='hapus_pelanggan'),
    path('api/pelanggan/belum_nota/<int:p_id>/', item_belum_nota, name='item_belum_nota'),
    path('api/nota/buat/', buat_nota, name='buat_nota'),
    
    path('api/kas/info/', info_kas, name='info_kas'),
    path('api/kas/tambah/', tambah_saldo, name='tambah_saldo'),
    path('api/kasbon/transaksi/', transaksi_kasbon, name='transaksi_kasbon'),
    path('api/kasbon/history/<int:pelanggan_id>/', history_kasbon_pelanggan, name='history_kasbon_pelanggan'),
    path('api/petani/profil/<int:pelanggan_id>/', profil_petani, name='profil_petani'),
    path('api/tanggungan/list/', list_tanggungan, name='list_tanggungan'),
    path('api/tanggungan/lunasin_bb/', lunasin_bb, name='lunasin_bb'),
    path('api/tanggungan/selesai_tf/', selesaikan_tf, name='selesaikan_tf'),
    
    path('api/pengeluaran/tonase/', info_tonase, name='info_tonase'),
    path('api/pengeluaran/tambah/', tambah_pengeluaran, name='tambah_pengeluaran'),
    path('api/laporan/', laporan_harian, name='laporan_harian'),
    path('api/laporan/edit/', edit_transaksi, name='edit_transaksi'),
    path('api/laporan/hapus_nota/', hapus_nota, name='hapus_nota'),
    path('api/laporan/hapus_transaksi/', hapus_transaksi, name='hapus_transaksi'),
    path('api/kasbon/hapus_entry/', hapus_kasbon_entry, name='hapus_kasbon_entry'),
    path('api/pengiriman/hapus/', hapus_pengiriman, name='hapus_pengiriman'),
    
    path('api/pengiriman/aktif/', list_pengiriman_aktif, name='list_pengiriman_aktif'),
    path('api/pengiriman/buat/', buat_pengiriman, name='buat_pengiriman'),
    path('api/pengiriman/item/edit/', edit_item_pengiriman, name='edit_item_pengiriman'),
    path('api/pengiriman/item/hapus/', hapus_item_pengiriman, name='hapus_item_pengiriman'),
    path('api/pengiriman/detail/<int:p_id>/', detail_pengiriman, name='detail_pengiriman'),
    path('api/pengiriman/item/tambah/', tambah_item_pengiriman, name='tambah_item_pengiriman'),
    path('api/pengiriman/finalisasi/', finalisasi_pengiriman, name='finalisasi_pengiriman'),
    path('api/pengiriman/laporan/', laporan_pengiriman, name='laporan_pengiriman'),
    
    path('api/lot/', get_lots, name='get_lots'),
    path('api/lot/buat/', buat_lot, name='buat_lot'),
    path('api/lot/edit/', edit_lot, name='edit_lot'),      
    path('api/lot/hapus/', hapus_lot, name='hapus_lot'),
    path('api/lot/detail/<int:lot_id>/', get_lot_detail, name='get_lot_detail'),
    path('api/pengiriman/edit_pabrik/', edit_pengiriman_pabrik, name='edit_pengiriman_pabrik'),
    path('api/login/', api_login, name='api_login'),
    path('api/log_aktivitas/', list_log_aktivitas, name='list_log_aktivitas'),
    path('api/prediksi_ai/', prediksi_harga_ai, name='prediksi_harga_ai'),
]