# Generated by Django 4.2.29 on 2026-03-16 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KasGudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('tipe_mutasi', models.CharField(choices=[('MASUK', 'Uang Masuk'), ('KELUAR', 'Uang Keluar')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('berat_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('biaya_materai', models.DecimalField(decimal_places=2, default=6000, max_digits=10)),
                ('status_bayar', models.CharField(choices=[('LUNAS', 'Lunas'), ('BB', 'Belum Bayar (BB)')], default='LUNAS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('saldo_mengendap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_kasbon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('kategori', models.CharField(choices=[('MAKAN', 'Uang Makan'), ('BURUH', 'Ongkos Buruh Harian'), ('ONGKIR', 'Ongkos Kirim'), ('BURUH_TAMBAHAN', 'Buruh Tambahan'), ('UANG_JALAN', 'Uang Jalan'), ('MINYAK', 'Minyak Mobil'), ('SUMBANGAN', 'Sumbangan'), ('GAJI', 'Gaji Bulanan'), ('LAIN', 'Lain-lain')], max_length=20)),
                ('nominal_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(help_text='Isi detail seperti plat mobil, nama karyawan, atau jumlah orang')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('AMPERA', 'Ampera')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_bayar', models.DateTimeField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('is_setoran_pinjaman', models.BooleanField(default=False)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operasional.nota')),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operasional.pelanggan'),
        ),
        migrations.CreateModel(
            name='BukuKasbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('tipe_transaksi', models.CharField(choices=[('PINJAM', 'Pinjaman Baru'), ('SETOR', 'Setoran')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.CharField(max_length=255)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operasional.pelanggan')),
            ],
        ),
    ]
