# Generated by Django 4.2.29 on 2026-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='pakai_buruh',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='pakai_komisi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='pakai_materai',
            field=models.BooleanField(default=True),
        ),
    ]
