# Generated by Django 4.2.29 on 2026-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0002_nota_pakai_buruh_nota_pakai_komisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='is_selesai',
            field=models.BooleanField(default=False),
        ),
    ]
