# Generated by Django 4.2.29 on 2026-03-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0003_pembayaran_is_selesai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('KIRIM', 'Kirim Mobil'), ('STOCK', 'Timbang Taruh')], max_length=10)),
                ('plat_mobil', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_stock', models.CharField(blank=True, max_length=20, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Sedang Dimuat'), ('TERKIRIM', 'Selesai/Terkirim')], default='DRAFT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tujuan', models.CharField(max_length=100)),
                ('tonase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_input', models.DecimalField(decimal_places=2, max_digits=15)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operasional.pengiriman')),
            ],
        ),
    ]
