# Generated by Django 4.2.29 on 2026-03-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0004_pengiriman_itempengiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempengiriman',
            name='is_dibuat_nota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempengiriman',
            name='pelanggan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operasional.pelanggan'),
        ),
        migrations.AlterField(
            model_name='itempengiriman',
            name='nama_tujuan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
