# Generated by Django 4.2.29 on 2026-03-18 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0005_itempengiriman_is_dibuat_nota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotPabrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lot', models.CharField(max_length=100)),
                ('tanggal_buat', models.DateField(default=django.utils.timezone.now)),
                ('pabrik', models.CharField(blank=True, max_length=100, null=True)),
                ('kilo_pabrik', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bl', models.CharField(blank=True, max_length=50, null=True)),
                ('vm', models.CharField(blank=True, max_length=50, null=True)),
                ('is_selesai', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengiriman_set', to='operasional.lotpabrik'),
        ),
    ]
