# Generated by Django 4.2.29 on 2026-03-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0006_lotpabrik_pengiriman_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotpabrik',
            name='bl',
        ),
        migrations.RemoveField(
            model_name='lotpabrik',
            name='kilo_pabrik',
        ),
        migrations.RemoveField(
            model_name='lotpabrik',
            name='pabrik',
        ),
        migrations.RemoveField(
            model_name='lotpabrik',
            name='vm',
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='bl_pabrik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='pabrik_tujuan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='tonase_pabrik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='vm_pabrik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
