# Generated by Django 4.2.29 on 2026-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0007_remove_lotpabrik_bl_remove_lotpabrik_kilo_pabrik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengiriman',
            name='bl_pabrik',
        ),
        migrations.RemoveField(
            model_name='pengiriman',
            name='pabrik_tujuan',
        ),
        migrations.RemoveField(
            model_name='pengiriman',
            name='vm_pabrik',
        ),
        migrations.AddField(
            model_name='lotpabrik',
            name='bl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lotpabrik',
            name='pabrik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lotpabrik',
            name='vm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
