# Generated by Django 4.2.29 on 2026-05-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0009_userprofile_logaktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='item_pengiriman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_set', to='operasional.itempengiriman'),
        ),
    ]
