# Generated by Django 4.2.29 on 2026-05-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0010_nota_item_pengiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='no_rekening',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='no_telp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
